server:
  port: 8081
  
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: false
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/MICROSERVICEDEV?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    