server:
  port: 8080
zuul:
  routes:
    training:
      path: /training/**
      url: http://localhost:8081/training
    user:
      path: /user/**
      url: http://localhost:8082/user
    common:
      path: /common/**
      url: http://localhost:8083/user
      
token:
  validation-path: /training/*; /common/*
  
user:
  service: http://localhost:8082